### ISSUE TITLE
Zmiana linku przy wyświetlaniu tablicy - nie można zobaczyć ID przystanku

### ISSUE THREAD

**Issue by TheLegend2137** [PiotrMachowski/Home-Assistant-custom-components-MPK-Lodz#2]
Zmienił się link przy wyświetlaniu tablic z rozkładem, zamiast http://rozklady.lodz.pl/Home/TimeTableReal?busStopId=1234 wygląda to tak http://rozklady.lodz.pl/Home/TimeTableReal?busStopNum=1234, linki z id nadal działają, więc integracja działa dla kogoś, kto skonfigurował wszystko przed tą zmianą, ale nie można nigdzie znaleźć id przystanków jeśli nie znaliśmy ich wcześniej. Dane pomiędzy tymi dwoma stronami wyglądają identycznie, więc wydaje mi się, że można rozwiązać to, zmieniając link w kodzie integracji, jednak nie udało mi się sprawić, żeby wszystko działało z nowym linkiem.

**Comment by PiotrMachowski** [comment]
Zmieniłem tutaj i u mnie wszystko działa, mogę prosić o konfigurację, która robi problemy?
https://github.com/PiotrMachowski/Home-Assistant-custom-components-MPK-Lodz/blob/master/custom_components/mpk_lodz/sensor.py#L177

```diff
    @staticmethod
    def get_data(stop_id):
-       address = "http://rozklady.lodz.pl/Home/GetTimeTableReal?busStopId={}".format(stop_id)
+       address = "http://rozklady.lodz.pl/Home/GetTimeTableReal?busStopNum={}".format(stop_id)
        headers = {
            'referer': address,
        }
        response = requests.get(address, headers=headers)
```

**Comment by TheLegend2137** [comment]
Faktycznie wszystko działa, wydaje mi się, że powodem mogło być edytowanie integracji pobranej przez hacs, odinstalowałem i zainstalowałem manualnie i wszystko działa idealnie, dzięki za pomoc, świetna integracja swoją drogą.

**Comment by PiotrMachowski** [comment]
Naprawione w v1.0.2
